// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc253.Pneumatics;

import org.usfirst.frc253.Pneumatics.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    
	public Joystick leftJoystick;
	public Joystick rightJoystick;
	
	public JoystickButton ActCompress;
	public JoystickButton ActSolenoid1Forward;
	public JoystickButton ActSolenoid1Reverse;
	public JoystickButton GetCompressData;
	
	
    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    	leftJoystick = new Joystick(0);
    	rightJoystick = new Joystick(1);

        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("ActCompress", new ActCompress());
        SmartDashboard.putData("Solenoid 1 Forward", new ActSolenoid1Forward());
        SmartDashboard.putData("GetCompressData", new GetCompressData());
        SmartDashboard.putData("StopCompress", new StopCompress());
        SmartDashboard.putData("Solenoid 1 Off", new Solenoid1Off());
        SmartDashboard.putData("Solenoid 1 Reverse", new ActSolenoid1Reverse());
        SmartDashboard.putData("Solenoid 2 Forward", new ActSolenoid2Forward());
        SmartDashboard.putData("Solenoid 2 Reverse", new ActSolenoid2Reverse());
        SmartDashboard.putData("Solenoid 2 Off", new Solenoid2Off());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
    public Joystick getLeftJoystick() {
        return leftJoystick;
    }

    public Joystick getRightJoystick() {
        return rightJoystick;
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

