// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc253.Pneumatics;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.Solenoid;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	//Declarations of Compressor(s) and Double Solenoid(s)
    public static Compressor pneumaticsCompressor1;
    public static DoubleSolenoid pneumaticsDoubleSolenoid1;
    public static DoubleSolenoid pneumaticsDoubleSolenoid2;
    public static DoubleSolenoid pneumaticsDoubleSolenoid3;
    public static Relay pneumaticsRelaySolenoid;
    
    //Declares Drivetrain Ports
    public static final int driveMotorLeft = 2; // 2
   	public static final int driveMotorLeft_Back = 3; //3
   	public static final int driveMotorRight = 0; //0
   	public static final int driveMotorRight_Back = 1; //1
   	
    //Drive train directions
   	public static final int driveMotorLeftDir = -1; //-1
   	public static final int driveMotorRightDir = 1; //1
   	public static final int driveMotorRightBackDir = 1; //1
   	public static final int driveMotorLeftBackDir = -1; //-1

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        pneumaticsCompressor1 = new Compressor(0);
        
        
        pneumaticsDoubleSolenoid1 = new DoubleSolenoid(0, 2, 3);
//        pneumaticsRelaySolenoid = new Relay(4);
        pneumaticsDoubleSolenoid2 = new DoubleSolenoid(0, 4, 1);
        
        pneumaticsDoubleSolenoid3 = new DoubleSolenoid(0, 5, 6);
        
        
//        LiveWindow.addActuator("Pneumatics", "Double Solenoid 1", pneumaticsDoubleSolenoid1);
//        LiveWindow.addActuator("Pneumatics",  "Double Solenoid 2", pneumaticsDoubleSolenoid2);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
