// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc253.Pneumatics.subsystems;

import org.usfirst.frc253.Pneumatics.RobotMap;
import org.usfirst.frc253.Pneumatics.commands.*;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Pneumatics extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public final Compressor compressor = RobotMap.pneumaticsCompressor1;
//    public final Solenoid doubleSolenoid = RobotMap.pneumaticsDoubleSolenoid1;
    public final DoubleSolenoid doubleSolenoid1 = RobotMap.pneumaticsDoubleSolenoid2;
//    public final Relay relay = RobotMap.pneumaticsRelaySolenoid;
    
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {}
    
    public Pneumatics(){
    	super();
    	CompressStart();
    	CompressStop();
    	SolenoidForward();
    	SolenoidReverse();
    	SolenoidOff();
    }
    public void CompressStart(){
    	compressor.setClosedLoopControl(true);
    }
    public void CompressStop(){
    	compressor.setClosedLoopControl(false);
    }
    public void SolenoidForward(){
//    	relay.setDirection(Relay.Value.kForward);
//    	relay.set(Relay.Value.kOn);
    	doubleSolenoid1.set(DoubleSolenoid.Value.kForward);
    }
    public void SolenoidReverse(){
//    	doubleSolenoid.set(DoubleSolenoid.Value.kReverse);
    	doubleSolenoid1.set(DoubleSolenoid.Value.kReverse);
    }
    public void SolenoidOff(){
//    	relay.set(Relay.Value.kOff);
    	doubleSolenoid1.set(DoubleSolenoid.Value.kOff);
    }
}

